App\Entity\Books\Book:
    type: entity
    table: books
    schema: db_api_books
#    repositoryClass: App\Repository\Books\BookRepository
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        description:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
        price:
            type: integer
            nullable: false
            options:
                unsigned: true
        authorId:
            type: integer
            nullable: true
            options:
                unsigned: true
            column: author_id
        createdAt:
            type: datetime
            nullable: false
            options:
                default: CURRENT_TIMESTAMP
            column: created_at
        updatedAt:
            type: datetime
            nullable: true
            options:
                default: CURRENT_TIMESTAMP
            column: updated_at
    manyToOne:
        author:
            #targetEntity: Author
            targetEntity: App\Model\AuthorInterface
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                author_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
